"""
Rule models — the Behavioral Rule Engine's data layer.

A Rule is an explicit behavioral standard derived from observed correction patterns.
Rules flow through a lifecycle: PROPOSED → ACTIVE → (PAUSED | ARCHIVED).
Only Admin+ users can confirm (activate) a rule.
"""

from datetime import UTC, datetime
from enum import Enum

from pydantic import BaseModel, Field
from ulid import ULID


def _new_id(prefix: str) -> str:
    return f"{prefix}_{ULID()}"


# ── Enums ─────────────────────────────────────────────────────────────────────

class RuleStatus(str, Enum):
    PROPOSED = "proposed"       # Generated by pattern mining, awaiting human review
    ACTIVE = "active"           # Confirmed by a human admin, being injected
    PAUSED = "paused"           # Temporarily disabled by an admin
    DEPRECATED = "deprecated"   # Superseded by a newer rule
    ARCHIVED = "archived"       # Auto-archived after 90 days without supporting evidence


class RuleType(str, Enum):
    BEHAVIORAL = "behavioral"   # How the AI should behave in a context
    PROHIBITION = "prohibition" # What the AI must never do
    ENTITY = "entity"           # How the AI should treat a specific entity
    FORMAT = "format"           # How outputs should be structured


# ── Core models ───────────────────────────────────────────────────────────────

class Rule(BaseModel):
    """A confirmed or proposed behavioral standard stored in the CCG and injected via context API."""
    rule_id: str = Field(default_factory=lambda: _new_id("rule"))
    workspace_id: str
    text: str
    """Plain English rule statement. One sentence. Be specific."""

    rule_type: RuleType
    tool_scope: list[str] = Field(default_factory=lambda: ["*"])
    """List of tool identifiers this rule applies to. ['*'] = all tools."""

    context_scope: dict[str, str] = Field(default_factory=dict)
    """Conditions under which this rule activates. E.g. {'jurisdiction': 'US'}."""

    confidence: float = Field(default=0.8, ge=0.0, le=1.0)
    """Decays over time without supporting corrections. Refreshed on each new supporting event."""

    status: RuleStatus = RuleStatus.PROPOSED

    confirmed_by: str | None = None
    """actor_id of the Admin who confirmed this rule."""

    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    last_supported: datetime | None = None
    """Timestamp of the most recent correction event supporting this rule."""

    source_corrections: list[str] = Field(default_factory=list)
    """event_ids of corrections that contributed to this rule."""

    invocation_count: int = 0
    """How many times this rule has been included in a context injection response."""

    superseded_by: str | None = None
    """rule_id of the rule that replaced this one, if deprecated."""


class RuleProposal(BaseModel):
    """
    A candidate rule generated by the Pattern Mining Engine.
    Stored temporarily until an Admin reviews it.
    Stored separately from Rule so the proposal can be dismissed without creating a Rule node.
    """
    proposal_id: str = Field(default_factory=lambda: _new_id("prop"))
    workspace_id: str
    rule_text: str
    rule_type: RuleType
    tool_scope: list[str]
    context_scope: dict[str, str]
    source_corrections: list[str]

    pattern_confidence: float
    """Confidence score of the underlying pattern cluster."""

    llm_confidence: float
    """LLM's self-reported confidence in the generated rule statement."""

    explanation: str
    """Why this pattern was detected — shown to the human reviewer."""

    example_summaries: list[str] = Field(default_factory=list)
    """2-3 representative correction summaries from the cluster (privacy-safe)."""

    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    reviewed: bool = False


# ── API input models ──────────────────────────────────────────────────────────

class RuleConfirmRequest(BaseModel):
    """Body for POST /v1/rules/{proposal_id}/confirm"""
    confirmed_by: str
    text: str | None = None
    """Optionally override the LLM-generated text before confirming."""

    tool_scope: list[str] | None = None
    context_scope: dict[str, str] | None = None


class RuleUpdateRequest(BaseModel):
    """Body for PATCH /v1/rules/{rule_id}"""
    text: str | None = None
    tool_scope: list[str] | None = None
    context_scope: dict[str, str] | None = None
    status: RuleStatus | None = None


class RuleListResponse(BaseModel):
    """Paginated rule list."""
    items: list[Rule]
    total: int
    page: int
    page_size: int
