"""
Proposals API — rule proposals awaiting human review.

GET  /v1/proposals                         — list pending proposals for a workspace
POST /v1/proposals/{proposal_id}/confirm   — confirm → creates active rule
POST /v1/proposals/{proposal_id}/dismiss   — discard without creating a rule

Proposals are auto-generated by the Pattern Mining Engine.
Separated from /v1/rules to avoid FastAPI wildcard routing conflicts.
"""

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncConnection

from app.database.postgres import get_connection
from app.models.rules import Rule, RuleConfirmRequest, RuleConfirmResponse, RuleProposal
from app.services.rule_engine import RuleEngineService

router = APIRouter()


@router.get(
    "",
    response_model=list[RuleProposal],
    summary="List pending rule proposals",
)
async def list_proposals(
    workspace_id: str,
    conn: AsyncConnection = Depends(get_connection),
) -> list[RuleProposal]:
    service = RuleEngineService(conn)
    return await service.list_proposals(workspace_id)


@router.post(
    "/{proposal_id}/confirm",
    response_model=RuleConfirmResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Confirm a proposed rule (Admin+ only)",
    description=(
        "Confirms a rule proposal, creating an active behavioral rule. "
        "Automatically runs conflict detection against existing active rules via Groq LLM. "
        "If conflicts are found, both the new rule and the conflicting rule(s) are set to "
        "status='conflict' and returned in `conflicts_detected`. "
        "Resolve conflicts via POST /v1/rules/{rule_id}/resolve-conflict."
    ),
)
async def confirm_proposal(
    proposal_id: str,
    body: RuleConfirmRequest,
    conn: AsyncConnection = Depends(get_connection),
) -> RuleConfirmResponse:
    service = RuleEngineService(conn)
    result = await service.confirm_proposal(proposal_id, body)
    if not result:
        raise HTTPException(
            status_code=404,
            detail=f"Proposal {proposal_id!r} not found or already reviewed.",
        )
    return result


@router.post(
    "/{proposal_id}/dismiss",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Dismiss a rule proposal without creating a rule",
)
async def dismiss_proposal(
    proposal_id: str,
    conn: AsyncConnection = Depends(get_connection),
) -> None:
    service = RuleEngineService(conn)
    ok = await service.dismiss_proposal(proposal_id)
    if not ok:
        raise HTTPException(
            status_code=404,
            detail=f"Proposal {proposal_id!r} not found.",
        )
