-- ============================================================
-- Lore — PostgreSQL initial schema
-- Migration: 001_initial
-- Run with: psql $DATABASE_URL -f migrations/001_initial.sql
-- Compatible with Supabase Free tier
-- ============================================================

-- ── Extensions ────────────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "pgcrypto";  -- gen_random_uuid() fallback

-- ── correction_events ─────────────────────────────────────────────────────────
-- Core event log. Every human-AI correction flows through here.
-- Privacy: raw content is NEVER stored — only structured deltas and metadata.

CREATE TABLE IF NOT EXISTS correction_events (
    event_id            TEXT        PRIMARY KEY,            -- evt_ULID
    workspace_id        TEXT        NOT NULL,
    tool                TEXT        NOT NULL,               -- ToolName enum
    event_type          TEXT        NOT NULL,               -- EventType enum
    actor_id            TEXT        NOT NULL,               -- Pseudonymized HMAC of user ID
    ai_output_id        TEXT,                               -- Reference to originating AI output
    context_tags        JSONB       NOT NULL DEFAULT '{}',  -- {'customer_tier': 'enterprise', ...}
    delta               JSONB       NOT NULL DEFAULT '[]',  -- Array of CorrectionDelta objects
    confidence_signal   REAL        NOT NULL DEFAULT 1.0,
    session_id          TEXT,
    external_ref        TEXT,                               -- Source tool's native ID
    timestamp           TIMESTAMPTZ NOT NULL DEFAULT now(),
    processed           BOOLEAN     NOT NULL DEFAULT FALSE,  -- True after pattern mining
    processing_version  TEXT
);

-- Indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_events_workspace_ts
    ON correction_events (workspace_id, timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_events_actor
    ON correction_events (workspace_id, actor_id);

CREATE INDEX IF NOT EXISTS idx_events_tool
    ON correction_events (workspace_id, tool);

CREATE INDEX IF NOT EXISTS idx_events_ai_output
    ON correction_events (ai_output_id) WHERE ai_output_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_events_unprocessed
    ON correction_events (workspace_id, processed) WHERE processed = FALSE;

-- ── rules ─────────────────────────────────────────────────────────────────────
-- Confirmed behavioral standards (mirrored in Neo4j for graph queries).

CREATE TABLE IF NOT EXISTS rules (
    rule_id             TEXT        PRIMARY KEY,            -- rule_ULID
    workspace_id        TEXT        NOT NULL,
    text                TEXT        NOT NULL,
    rule_type           TEXT        NOT NULL,               -- behavioral | prohibition | entity | format
    tool_scope          JSONB       NOT NULL DEFAULT '["*"]',
    context_scope       JSONB       NOT NULL DEFAULT '{}',
    confidence          REAL        NOT NULL DEFAULT 0.8,
    status              TEXT        NOT NULL DEFAULT 'proposed',
    confirmed_by        TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_supported      TIMESTAMPTZ,
    source_corrections  JSONB       NOT NULL DEFAULT '[]',
    invocation_count    INTEGER     NOT NULL DEFAULT 0,
    superseded_by       TEXT        REFERENCES rules(rule_id)
);

CREATE INDEX IF NOT EXISTS idx_rules_workspace_status
    ON rules (workspace_id, status);

CREATE INDEX IF NOT EXISTS idx_rules_active
    ON rules (workspace_id, confidence DESC) WHERE status = 'active';

-- ── rule_proposals ─────────────────────────────────────────────────────────────
-- Candidate rules generated by the Pattern Mining Engine, awaiting human review.

CREATE TABLE IF NOT EXISTS rule_proposals (
    proposal_id         TEXT        PRIMARY KEY,            -- prop_ULID
    workspace_id        TEXT        NOT NULL,
    rule_text           TEXT        NOT NULL,
    rule_type           TEXT        NOT NULL,
    tool_scope          JSONB       NOT NULL DEFAULT '["*"]',
    context_scope       JSONB       NOT NULL DEFAULT '{}',
    source_corrections  JSONB       NOT NULL DEFAULT '[]',
    pattern_confidence  REAL        NOT NULL,
    llm_confidence      REAL        NOT NULL DEFAULT 0.8,
    explanation         TEXT        NOT NULL DEFAULT '',
    example_summaries   JSONB       NOT NULL DEFAULT '[]',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    reviewed            BOOLEAN     NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_proposals_workspace_pending
    ON rule_proposals (workspace_id, created_at DESC) WHERE reviewed = FALSE;

-- ── entities ─────────────────────────────────────────────────────────────────
-- Entity memory profiles (mirrored in Neo4j for relationship traversal).

CREATE TABLE IF NOT EXISTS entities (
    entity_id               TEXT        PRIMARY KEY,        -- ent_ULID
    workspace_id            TEXT        NOT NULL,
    name                    TEXT        NOT NULL,
    name_lower              TEXT        NOT NULL,           -- Normalized for dedup
    entity_type             TEXT        NOT NULL,
    facts                   JSONB       NOT NULL DEFAULT '[]',
    linked_corrections      JSONB       NOT NULL DEFAULT '[]',
    linked_decisions        JSONB       NOT NULL DEFAULT '[]',
    linked_rules            JSONB       NOT NULL DEFAULT '[]',
    correction_rate         REAL,
    is_stale                BOOLEAN     NOT NULL DEFAULT FALSE,
    is_permanently_relevant BOOLEAN     NOT NULL DEFAULT FALSE,
    mention_count           INTEGER     NOT NULL DEFAULT 0,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_updated            TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (workspace_id, name_lower)
);

CREATE INDEX IF NOT EXISTS idx_entities_workspace
    ON entities (workspace_id, last_updated DESC);

CREATE INDEX IF NOT EXISTS idx_entities_type
    ON entities (workspace_id, entity_type);

CREATE INDEX IF NOT EXISTS idx_entities_active
    ON entities (workspace_id) WHERE is_stale = FALSE;

-- ── workspaces ───────────────────────────────────────────────────────────────
-- Minimal workspace record. Full workspace management is handled by Clerk.

CREATE TABLE IF NOT EXISTS workspaces (
    workspace_id    TEXT        PRIMARY KEY,
    name            TEXT        NOT NULL,
    plan            TEXT        NOT NULL DEFAULT 'starter',  -- starter | growth | enterprise
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    settings        JSONB       NOT NULL DEFAULT '{}'
);

-- ── decisions ────────────────────────────────────────────────────────────────
-- Decision Log entries — intentional, human-authored records.

CREATE TABLE IF NOT EXISTS decisions (
    decision_id         TEXT        PRIMARY KEY,            -- dec_ULID
    workspace_id        TEXT        NOT NULL,
    title               TEXT        NOT NULL,
    what_was_decided    TEXT        NOT NULL,
    why                 TEXT,
    alternatives        JSONB       NOT NULL DEFAULT '[]',
    expected_outcome    TEXT,
    outcome_notes       TEXT,
    made_by             TEXT        NOT NULL,               -- actor_id
    category            TEXT        NOT NULL DEFAULT 'other',
    status              TEXT        NOT NULL DEFAULT 'active',
    date                DATE        NOT NULL DEFAULT CURRENT_DATE,
    linked_entities     JSONB       NOT NULL DEFAULT '[]',
    linked_corrections  JSONB       NOT NULL DEFAULT '[]',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_decisions_workspace
    ON decisions (workspace_id, date DESC);

CREATE INDEX IF NOT EXISTS idx_decisions_active
    ON decisions (workspace_id) WHERE status = 'active';

-- ── audit_chronicle ───────────────────────────────────────────────────────────
-- Immutable compliance record. Rows are append-only — no UPDATE allowed.
-- Hash chain for tamper detection (EU AI Act compliance).

CREATE TABLE IF NOT EXISTS audit_chronicle (
    audit_id        TEXT        PRIMARY KEY,                -- aud_ULID
    workspace_id    TEXT        NOT NULL,
    event_type      TEXT        NOT NULL,                   -- 'ai_output' | 'correction' | 'rule_confirmed' | 'decision_logged'
    event_ref_id    TEXT        NOT NULL,                   -- ID of the referenced event/rule/decision
    actor_id        TEXT,
    tool            TEXT,
    context_snap    JSONB       NOT NULL DEFAULT '{}',      -- Snapshot of active rules at time of event
    record_hash     TEXT        NOT NULL,                   -- SHA-256 hash of this record's content
    prev_hash       TEXT,                                   -- Hash of the previous record (chain)
    recorded_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Audit records are append-only — enforce with a rule or application-level check
CREATE INDEX IF NOT EXISTS idx_audit_workspace_ts
    ON audit_chronicle (workspace_id, recorded_at DESC);

-- ============================================================
-- Seed: create a default local development workspace
-- ============================================================
INSERT INTO workspaces (workspace_id, name, plan)
VALUES ('ws_local_dev', 'Local Development', 'starter')
ON CONFLICT (workspace_id) DO NOTHING;
